### ISSUE TITLE
Status code 404, {"error":{"code":"404","message": "Resource not found"}}

### ISSUE THREAD

**Issue by vcuomo74** [MicrosoftDocs/azure-docs.it-it#422]
Hi,
I'm running the example provided in this page but I always get the exception below.
I've tried my COMPUTER_VISION_SUBSCRIPTION_KEY and COMPUTER_VISION_ENDPOINT (i.e. "https://westcentralus.api.cognitive.microsoft.com/vision") on https://westcentralus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/56f91f2e778daf14a499e1fc/console and everything is FINE!
How can I solve this issue?
Thanks

Status code 404, {"error":{"code":"404","message": "Resource not found"}}
com.microsoft.azure.cognitiveservices.vision.computervision.models.ComputerVisionErrorException: Status code 404, {"error":{"code":"404","message": "Resource not found"}}
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
                at java.lang.reflect.Constructor.newInstance(Unknown Source)
                at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
                at com.microsoft.azure.AzureResponseBuilder.build(AzureResponseBuilder.java:56)
                at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl.recognizePrintedTextDelegate(ComputerVisionImpl.java:1994)
                at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl.access$1200(ComputerVisionImpl.java:71)
                at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl$38.call(ComputerVisionImpl.java:1981)
                at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl$38.call(ComputerVisionImpl.java:1977)
                at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
                at retrofit2.adapter.rxjava.CallArbiter.deliverResponse(CallArbiter.java:120)
                at retrofit2.adapter.rxjava.CallArbiter.emitResponse(CallArbiter.java:102)
                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:46)
                at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
                at rx.Observable.unsafeSubscribe(Observable.java:10327)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
                at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                at rx.Observable.subscribe(Observable.java:10423)
                at rx.Observable.subscribe(Observable.java:10390)
                at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443)
                at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
                at com.microsoft.azure.cognitiveservices.vision.computervision.implementation.ComputerVisionImpl$ComputerVisionRecognizePrintedTextParameters.execute(ComputerVisionImpl.java:2039)
                at com.st.microsoft.demo.ComputerVisionQuickstart.RecognizeTextOCRRemote(ComputerVisionQuickstart.java:277)
                at com.st.microsoft.demo.ComputerVisionQuickstart.main(ComputerVisionQuickstart.java:70)

 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: d8815595-4c76-7c52-2d2c-dcbdd635bcea
* Version Independent ID: 723dfef2-1e9f-478d-1fa4-06254c8d41fc
* Content: [Avvio rapido: Libreria client di Visione artificiale per Java](https://docs.microsoft.com/it-it/azure/cognitive-services/computer-vision/quickstarts-sdk/java-sdk#feedback)
* Content Source: [articles/cognitive-services/Computer-vision/quickstarts-sdk/java-sdk.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cognitive-services/Computer-vision/quickstarts-sdk/java-sdk.md)
* Service: **cognitive-services**
* Sub-service: **computer-vision**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by srvbpigh** [comment]
Hello, @vcuomo74
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47698](https://github.com/MicrosoftDocs/azure-docs/issues/47698) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @vcuomo74, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47698. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
